name: Publish Documentation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
